import type { EventInsight, MatchAnalysis, NewsItem, Prediction } from "./types";

export const events: EventInsight[] = [
  {
    id: "evt-football-001",
    sport: "football",
    league: "Primera Division",
    leagueId: "demo-chile-primera",
    country: "Chile",
    season: 2026,
    round: "Fecha 18",
    startsAt: "2026-07-13T20:30:00-04:00",
    status: "today",
    statusLabel: "Programado",
    home: {
      id: "team-scl",
      name: "Santiago Capital",
      shortName: "SCL",
      form: ["W", "D", "W", "L", "W"],
      country: "Chile",
      tablePosition: 2,
    },
    away: {
      id: "team-val",
      name: "Valparaiso Puerto",
      shortName: "VAL",
      form: ["D", "W", "L", "D", "W"],
      country: "Chile",
      tablePosition: 5,
    },
    venue: "Estadio Nacional",
    confidence: 82,
    modelVersion: "gsi-football-xg-0.3.1",
    source: {
      id: "src-opta-demo-001",
      provider: "Demo Sports Feed",
      collectedAt: "2026-07-13T12:05:00-04:00",
      normalizedVersion: "sports-normalizer-0.2.0",
    },
  },
  {
    id: "evt-basketball-014",
    sport: "basketball",
    league: "Liga Nacional",
    leagueId: "demo-chile-basket",
    country: "Chile",
    season: 2026,
    round: "Temporada regular",
    startsAt: "2026-07-13T22:00:00-04:00",
    status: "today",
    statusLabel: "Programado",
    home: {
      id: "team-andes",
      name: "Andes Hoops",
      shortName: "AND",
      form: ["W", "W", "W", "L", "W"],
      country: "Chile",
      tablePosition: 1,
    },
    away: {
      id: "team-sur",
      name: "Sur Basket",
      shortName: "SUR",
      form: ["L", "W", "D", "W", "L"],
      country: "Chile",
      tablePosition: 6,
    },
    venue: "Arena Metropolitana",
    confidence: 76,
    modelVersion: "gsi-basket-pace-0.2.4",
    source: {
      id: "src-stats-demo-014",
      provider: "Demo Court Feed",
      collectedAt: "2026-07-13T12:10:00-04:00",
      normalizedVersion: "sports-normalizer-0.2.0",
    },
  },
  {
    id: "evt-tennis-102",
    sport: "tennis",
    league: "ATP 500",
    leagueId: "demo-atp-500",
    country: "International",
    season: 2026,
    round: "Cuartos de final",
    startsAt: "2026-07-14T11:00:00-04:00",
    status: "upcoming",
    statusLabel: "Programado",
    home: {
      id: "player-rios",
      name: "Mateo Rios",
      shortName: "RIO",
      form: ["W", "W", "L", "W", "W"],
      country: "Chile",
    },
    away: {
      id: "player-kovac",
      name: "Luka Kovac",
      shortName: "KOV",
      form: ["W", "L", "W", "W", "D"],
      country: "Croacia",
    },
    venue: "Cancha Central",
    confidence: 71,
    modelVersion: "gsi-tennis-surface-0.1.8",
    source: {
      id: "src-tennis-demo-102",
      provider: "Demo Rally Feed",
      collectedAt: "2026-07-13T11:40:00-04:00",
      normalizedVersion: "sports-normalizer-0.2.0",
    },
  },
];

export const matchAnalyses: MatchAnalysis[] = [
  {
    eventId: "evt-football-001",
    headline: "Santiago Capital llega con ligera ventaja por volumen ofensivo y mejor presion tras perdida.",
    favorite: "Santiago Capital",
    updatedAt: "2026-07-13T12:18:00-04:00",
    probabilities: {
      homeWin: 44,
      draw: 28,
      awayWin: 28,
    },
    projectedScore: {
      home: 1.62,
      away: 1.21,
      label: "1-1",
      interval: "Local 1-2 goles · Visitante 0-2 goles",
    },
    confidence: 72,
    riskLevel: "Medio",
    matchScore: 87,
    matchScoreLabel: "Excelente",
    matchScoreComponents: [
      { label: "Nivel competitivo", score: 86, explanation: "Ambos equipos se mantienen en zona alta." },
      { label: "Equilibrio", score: 82, explanation: "La diferencia de probabilidad principal es moderada." },
      { label: "Potencial ofensivo", score: 88, explanation: "Los dos generan volumen sostenido de remates." },
      { label: "Calidad de planteles", score: 84, explanation: "Planteles con profundidad similar por linea." },
      { label: "Importancia", score: 91, explanation: "Impacta posiciones directas de clasificacion." },
      { label: "Incertidumbre", score: 79, explanation: "Alineaciones sujetas a confirmacion oficial." },
    ],
    scorelines: [
      { label: "1-1", probability: 14 },
      { label: "2-1", probability: 11 },
      { label: "1-0", probability: 10 },
      { label: "0-1", probability: 9 },
      { label: "2-2", probability: 8 },
    ],
    simulations: {
      total: 10000,
      homeWins: 4380,
      draws: 2810,
      awayWins: 2810,
    },
    teamComparison: [
      { label: "Ataque", home: 88, away: 81 },
      { label: "Defensa", home: 80, away: 84 },
      { label: "Control", home: 86, away: 78 },
      { label: "Plantel", home: 84, away: 79 },
      { label: "Forma", home: 87, away: 73 },
      { label: "Transicion", home: 82, away: 77 },
    ],
    expectedStats: [
      { label: "Goles esperados", home: "1,62", away: "1,21" },
      { label: "Tiros", home: "13,2", away: "10,8" },
      { label: "Tiros al arco", home: "4,9", away: "3,7" },
      { label: "Posesion", home: "54%", away: "46%" },
      { label: "Corners", home: "5,1", away: "4,2" },
      { label: "Tarjetas", home: "1,8", away: "2,4" },
      { label: "Ambos marcan", home: "58%", away: "58%" },
    ],
    favorableFactors: [
      {
        label: "Volumen ofensivo reciente",
        impact: 31,
        value: "+2,4 tiros al arco vs promedio rival",
        direction: "positive",
        explanation: "El local sostiene mas llegadas claras durante los ultimos cinco partidos.",
        source: "Demo Sports Feed",
        updatedAt: "2026-07-13T12:05:00-04:00",
      },
      {
        label: "Presion alta",
        impact: 18,
        value: "64% recuperaciones en campo rival",
        direction: "positive",
        explanation: "Recupera antes y reduce posesiones largas del visitante.",
        source: "GSI feature store demo",
        updatedAt: "2026-07-13T12:08:00-04:00",
      },
    ],
    unfavorableFactors: [
      {
        label: "Defensa visitante en bloque bajo",
        impact: -14,
        value: "0,92 xG concedido",
        direction: "negative",
        explanation: "Valparaiso Puerto concede pocas ocasiones centradas cuando protege ventaja.",
        source: "Demo Sports Feed",
        updatedAt: "2026-07-13T12:05:00-04:00",
      },
    ],
    uncertainties: [
      {
        label: "Alineaciones no confirmadas",
        impact: -9,
        value: "2 titulares en evaluacion",
        direction: "uncertain",
        explanation: "La ausencia de un mediocampista cambia el peso de progresiones centrales.",
        source: "GSI Desk",
        updatedAt: "2026-07-13T11:50:00-04:00",
      },
    ],
    headToHead: [
      { date: "2026-04-03", competition: "Primera Division", home: "Valparaiso Puerto", away: "Santiago Capital", score: "1-1" },
      { date: "2025-11-21", competition: "Primera Division", home: "Santiago Capital", away: "Valparaiso Puerto", score: "2-1" },
      { date: "2025-08-09", competition: "Copa Chile", home: "Valparaiso Puerto", away: "Santiago Capital", score: "1-0" },
      { date: "2025-05-18", competition: "Primera Division", home: "Santiago Capital", away: "Valparaiso Puerto", score: "3-2" },
      { date: "2024-12-02", competition: "Primera Division", home: "Valparaiso Puerto", away: "Santiago Capital", score: "0-0" },
    ],
    predictiveMarkets: [
      { id: "demo-home-win", group: "Resultado", label: "Victoria SCL", value: "44%", confidence: 72 },
      { id: "demo-draw", group: "Resultado", label: "Empate", value: "28%", confidence: 72 },
      { id: "demo-away-win", group: "Resultado", label: "Victoria VAL", value: "28%", confidence: 72 },
      { id: "demo-home-or-draw", group: "Resultado", label: "SCL o empate", value: "72%", confidence: 72 },
      { id: "demo-btts", group: "Goles", label: "Ambos equipos marcan", value: "58%", confidence: 72 },
      { id: "demo-total-goals", group: "Goles", label: "Total de goles esperado", value: "2.83", detail: "SCL 1.62 · VAL 1.21", confidence: 72 },
      { id: "demo-over-15", group: "Goles", label: "Mas de 1.5 goles", value: "76%", confidence: 72 },
      { id: "demo-over-25", group: "Goles", label: "Mas de 2.5 goles", value: "54%", confidence: 72 },
      { id: "demo-shots", group: "Produccion", label: "Tiros", value: "SCL 13.2 · VAL 10.8" },
      { id: "demo-shots-on", group: "Produccion", label: "Tiros al arco", value: "SCL 4.9 · VAL 3.7" },
      { id: "demo-corners", group: "Produccion", label: "Corners", value: "SCL 5.1 · VAL 4.2" },
      { id: "demo-cards", group: "Disciplina", label: "Tarjetas", value: "SCL 1.8 · VAL 2.4" },
      { id: "demo-possession", group: "Control", label: "Posesion", value: "SCL 54% · VAL 46%" },
    ],
    featuredPlayers: [
      {
        id: "player-demo-001",
        name: "Lucas Andrade",
        team: "Santiago Capital",
        position: "Delantero",
        nationality: "Chile",
        score: 91,
        form: 88,
        projection: "Prob. gol 34% · 3,8 tiros",
        attributes: [
          { label: "Ataque", value: 91 },
          { label: "Definicion", value: 89 },
          { label: "Creacion", value: 82 },
          { label: "Presion", value: 84 },
          { label: "Impacto", value: 93 },
          { label: "Consistencia", value: 86 },
        ],
      },
      {
        id: "player-demo-002",
        name: "Tomas Rivera",
        team: "Valparaiso Puerto",
        position: "Mediocentro",
        nationality: "Chile",
        score: 87,
        form: 81,
        projection: "Prob. asistencia 19% · 2,4 pases clave",
        attributes: [
          { label: "Control", value: 88 },
          { label: "Pase", value: 90 },
          { label: "Defensa", value: 78 },
          { label: "Transicion", value: 83 },
          { label: "Impacto", value: 84 },
          { label: "Consistencia", value: 85 },
        ],
      },
    ],
  },
];

export const predictions: Prediction[] = [
  {
    eventId: "evt-football-001",
    predictedOutcome: "Santiago Capital con ventaja contextual",
    confidence: 82,
    probability: 0.58,
    modelVersion: "gsi-football-xg-0.3.1",
    generatedAt: "2026-07-13T12:15:00-04:00",
    factors: [
      {
        label: "Calidad de ocasiones",
        impact: 34,
        explanation: "El diferencial de xG reciente favorece al local en volumen y ubicacion de remates.",
      },
      {
        label: "Ritmo defensivo",
        impact: 21,
        explanation: "El visitante concede mas progresiones centrales en los ultimos 30 minutos.",
      },
      {
        label: "Localia",
        impact: 14,
        explanation: "El historial ajustado por rival muestra mejor control territorial en casa.",
      },
    ],
    caveats: ["La baja de un mediocampista titular reduce la certeza del modelo."],
  },
  {
    eventId: "evt-basketball-014",
    predictedOutcome: "Andes Hoops proyecta mejor eficiencia ofensiva",
    confidence: 76,
    probability: 0.55,
    modelVersion: "gsi-basket-pace-0.2.4",
    generatedAt: "2026-07-13T12:16:00-04:00",
    factors: [
      {
        label: "Pace ajustado",
        impact: 28,
        explanation: "El equipo local sostiene mas posesiones utiles sin elevar perdidas.",
      },
      {
        label: "Eficiencia de banca",
        impact: 19,
        explanation: "La segunda unidad produce margen positivo ante rotaciones similares.",
      },
      {
        label: "Rebote defensivo",
        impact: 17,
        explanation: "El visitante genera menos segundas oportunidades fuera de casa.",
      },
    ],
    caveats: ["La proyeccion depende de la disponibilidad del base titular."],
  },
  {
    eventId: "evt-tennis-102",
    predictedOutcome: "Mateo Rios se adapta mejor a la superficie",
    confidence: 71,
    probability: 0.53,
    modelVersion: "gsi-tennis-surface-0.1.8",
    generatedAt: "2026-07-13T12:20:00-04:00",
    factors: [
      {
        label: "Retorno en segundo saque",
        impact: 25,
        explanation: "Rios convierte mas puntos de presion sobre segundo servicio en esta superficie.",
      },
      {
        label: "Duracion de rallies",
        impact: 18,
        explanation: "La distribucion de rallies largos favorece su patron defensivo-ofensivo.",
      },
      {
        label: "Fatiga acumulada",
        impact: -9,
        explanation: "Kovac llega con menos minutos jugados durante la semana.",
      },
    ],
    caveats: ["Muestra historica limitada entre ambos jugadores."],
  },
];

export const news: NewsItem[] = [
  {
    id: "news-001",
    title: "Santiago Capital recupera presion alta antes del cruce principal",
    source: "GSI Desk",
    sport: "football",
    publishedAt: "2026-07-13T10:30:00-04:00",
  },
  {
    id: "news-002",
    title: "Andes Hoops mejora su rating neto en los ultimos cinco partidos",
    source: "GSI Desk",
    sport: "basketball",
    publishedAt: "2026-07-13T09:45:00-04:00",
  },
  {
    id: "news-003",
    title: "La superficie lenta cambia el peso del primer saque en ATP 500",
    source: "GSI Desk",
    sport: "tennis",
    publishedAt: "2026-07-13T08:20:00-04:00",
  },
];
